# Generated by Django 3.1.1 on 2020-11-29 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(null=True)),
            ],
            options={
                'db_table': 'playlist_entry',
            },
        ),
        migrations.CreateModel(
            name='NMLFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
            ],
            options={
                'db_table': 'nmlfile',
            },
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.TextField(null=True)),
                ('artist', models.TextField(null=True)),
                ('audio_id', models.TextField(null=True)),
                ('bitrate', models.IntegerField(null=True)),
                ('bpm', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
                ('comment2', models.TextField(null=True)),
                ('file', models.TextField(null=True)),
                ('import_date', models.DateField(null=True)),
                ('key', models.TextField(null=True)),
                ('last_played', models.DateField(null=True)),
                ('modified_date', models.DateField(null=True)),
                ('playcount', models.IntegerField(null=True)),
                ('playtime', models.FloatField(null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('genre', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('nml_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traktor_nml_viewer.nmlfile')),
            ],
            options={
                'db_table': 'collection_entry',
            },
        ),
    ]
