# Generated by Django 3.1.1 on 2020-09-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traktor_nml_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_played',
            field=models.TextField(null=True),
        ),
    ]
